# Generated by Django 4.2.2 on 2023-08-03 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0013_lead_date_added_lead_description_lead_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
