# Generated by Django 4.2.2 on 2023-08-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_agent_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agent',
            name='location',
        ),
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
