# Generated by Django 4.2.2 on 2023-08-03 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_remove_agent_location_user_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
